---
name: TestBranches
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - main


jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Check if PR into Master from Dev
        if: (github.base_ref == 'main' || github.event.pull_request.base.ref == 'main') && !(github.head_ref == 'dev' || github.event.pull_request.head.ref == 'dev')
        run: echo "can only pr to master from dev"


